##############################################
# generic ansible config information
##############################################
ansible_user: "devops"
bootstrap_user: "devops"
initial_remote_user: "root"

github_user_pubkeys:
  - parithosh
  - ralexstokes
  - djrtwo
  - skylenet
  - jwasinger
  - gballet
  - shivamagl95
  - barnabasbusa
  - samcm

ansible_python_interpreter: /usr/bin/python3
oh_my_zsh_config:
  PROMPT: "%{$fg[yellow]%}%n%{$fg[white]%}@%{$fg[red]%}%m%{$reset_color%} ${PROMPT}"

##############################################
#  common endpoints
##############################################
elendpoint: http://127.0.0.1:8545
beacon_api_endpoint: "http://127.0.0.1:{{beacon_api_port}}"

##############################################
# testnet specific information
##############################################
testnet_type: custom
eth2_network_name: beverly-hills-testnet
cl_network_name: beverly-hills-testnet
chainID: 90210
fee_recipient: "0xf97e180c050e5Ab072211Ad2C213Eb5AEE4DF134"

# enter bootnodes here if needed
bootnode_enrs:
  - "enr:-Iq4QJk4WqRkjsX5c2CXtOra6HnxN-BMXnWhmhEQO9Bn9iABTJGdjUOurM7Btj1ouKaFkvTRoju5vz2GPmVON2dffQKGAX53x8JigmlkgnY0gmlwhLKAlv6Jc2VjcDI1NmsxoQK6S-Cii_KmfFdUJL2TANL3ksaKUnNXvTCv1tLwXs0QgIN1ZHCCIyk"
  - "enr:-KG4QGA2Y7Mx6c3-1UZwsyDSbxDFH-sRZVTcLmljYza8fKaeYRxnu3prEnrLmPiiHF53f7mIgRkg2J8xyieUkry0l7EDhGV0aDKQTLYRfgAJAhL__________4JpZIJ2NIJpcIS8pkjaiXNlY3AyNTZrMaEDudzXlLg9IlQ3IcONn7Kh7AiU_FdqEd-ZhFxZYXd1H4-DdGNwgiMog3VkcIIjKA"
  - "enr:-Ly4QEjLiEIliBXT1GfcgaypBeRST3JWw6Q9ECDveqlDry8KF-pEk8x1TuHBiee0I4HsSkLzDy92r973_8cdaG_oqCYBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpBMthF-AAkCEv__________gmlkgnY0gmlwhKdHRsSJc2VjcDI1NmsxoQJQJjQR8e77nBy_uAMXcuBWWGnQx1rn3CKiPdF3gk3nsohzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA"

el_bootnode_enode:
  - "enode://906aaa403764b718fb6d23a80ad890eddfe6d33922eba7b9bc45e160e1079becd8f5f478f36607c7082d0e1015d43aec73ca35423e97ec69e5f55f0cfcd4f29f@188.166.72.218:3030"
  - "enode://99561977db2c6c24d6af793fb7c81ed16eccf37548c34590f4f973bbebe6b7ad297c8fbb1f7c7e12224a7e3f29ed5bd4c5a0d0a0d937a54eabee65173127ab50@167.71.70.196:30303"

##############################################
# metric information
##############################################
# enter pushgateway config if needed
prometheus_config_file: "prometheus/prometheus.yml.j2"
push_url: "https://victoriametrics.ethdevops.io/insert/0/prometheus/api/v1/write"
push_metrics_enabled: true
remote_write_auth: true
eth_metrics_exporter_enabled: true
cl_validator_metrics_enabled: false
eth_metrics_exporter_name: "metrics-exporter"
eth_metrics_exporter_image: "samcm/ethereum-metrics-exporter:0.17.0"
remote_write_username: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/eth2/monitoring/observability-cluster/metrics-ingress-users/beverly-hills.json | jq .username') }}"
remote_write_password: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/eth2/monitoring/observability-cluster/metrics-ingress-users/beverly-hills.json | jq .password') }}"

no_validator_keys: false
ethstats_url: "ethstats.beverlyhills.ethpandaops.io"
ethstats_password: "beverlyhills"

##############################################
# ports to configure
##############################################
el_rpc_port: 8545
el_ws_rpc_port: 8546
el_engine_port: 8551
node_exporter_web_listen_address: "127.0.0.1:9100"
prometheus_web_listen_address: "127.0.0.1:9101"
el_engine_snoop_port: 8560
beacon_api_port: 4000
beacon_metrics_port: 8000
beacon_p2p_port: 9000
validator_metrics_port: 8001
validator_rpc_port: 4002
el_metrics_port: 8002
eth_metrics_exporter_port: 8003

##############################################
# Command for JSON RPC snooper
##############################################
snoop_command: "./json_rpc_snoop -p {{el_engine_snoop_port}} http://127.0.0.1:{{el_engine_port}}"
snoop_image_name: parithoshj/json_rpc_snoop:v1.0.0-x86
snoop_container_name: snooper

##############################################
# name of the validator to display
##############################################
graffiti: "{{cl_client_name}}-{{el_client_name}}"

##############################################
# local data directories
##############################################
local_explorerdata_host_dir: "{{inventory_dir}}/../explorerdata"
local_explorerdata_host_archive: "{{inventory_dir}}/../explorerdata.tar.gz"
local_forkmondata_host_dir: "{{inventory_dir}}/../forkmondata"
local_forkmondata_host_archive: "{{inventory_dir}}/../forkmondata.tar.gz"
local_custom_config_data_host_dir: "{{inventory_dir}}/../custom_config_data"
local_custom_config_data_host_archive: "{{inventory_dir}}/../custom_config_data.tar.gz"
local_cl_config_filepath: "{{local_custom_config_data_host_dir}}/config.yaml"
local_mnemonics_filepath: "{{local_custom_config_data_host_dir}}/mnemonics.yaml"
# private dirs
# Validator assignments
local_validator_host_dir: "{{inventory_dir}}/../validator_prep/{{ansible_hostname}}"
local_validator_host_archive: "{{inventory_dir}}/../validator_prep/{{ansible_hostname}}.tar.gz"


##############################################
# remote host data directories
##############################################
home_dir: "/home/{{ ansible_user }}"
testnet_dir: "{{home_dir}}/custom_config_data"
el_node_dir: "{{home_dir}}/eldata"
beacon_node_dir: "{{home_dir}}/beacon"
validator_node_dir: "{{home_dir}}/validator"

##############################################
# common log config
##############################################
common_log_options:
  max-file: "10"
  max-size: 30m
  mode: non-blocking
  max-buffer-size: 4m
common_log_driver: json-file


##############################################
# container names
##############################################
beacon_container_name: beacon
validator_container_name: validator
execution_container_name: execution
hi_peer_count: 25
separate_validator_process_enabled: true

##############################################
# firewall rules
##############################################
firewall_allowed_tcp_ports:
  - 22
  - 30303
  - 80
  - 443
  - 9000

firewall_allowed_udp_ports:
  - 30303
  - 9000
  - 80
  - 443

firewall_additional_rules:
  - "iptables -A INPUT -p tcp --dport 8545 -s 188.166.72.218 -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 4000 -s 188.166.72.218 -j ACCEPT"