- name: Init beacon data dirs for nodes
  hosts: beacon
  gather_facts: false
  serial: 20
  tasks:
- name: Init el data dirs for nodes
  hosts: execution
  gather_facts: false
  serial: 20
  tasks:
    - name: Creates el dir
      file:
        path: "{{el_node_dir}}"
        state: directory
- name: Init testnet data dirs for nodes
  hosts: [beacon, execution, validator]
  gather_facts: false
  serial: 20
  tasks:
    - name: Creates testnet dir
      file:
        path: "{{testnet_dir}}"
        state: directory
