- name: Start landing_page
  hosts: landing_page
  gather_facts: true
  tasks:
    - name: Start landing_page
      docker_container:
        name: "{{ landing_page_container_name }}"
        state: started
        image: "{{ landing_page_image_name }}"
        pull: true
        restart_policy: unless-stopped
        network_mode: bridge
        ports:
          - "{{landing_page_port}}:1313"
        restart: "{{ landing_page_require_restart | default(false) }}"
        volumes: "{{ landing_page_volumes }}"