- name: Start forkmon
  hosts: forkmon
  gather_facts: true
  serial: 20
  tasks:
    - name: Start cl forkmon
      docker_container:
        name: "{{ forkmon_container_name }}"
        state: started
        image: "{{ forkmon_image_name }}"
        pull: true
        restart_policy: unless-stopped
        network_mode: bridge
        ports: # Cannot run on host network due to nginx proxy
          - "{{ forkmon_http_listen_port }}:8080"
        restart: "{{ forkmon_require_restart | default(false) }}"
        memory: "{{forkmon_memory}}"
        command: "{{ forkmon_start_args }}"
        volumes: "{{forkmon_volumes}}"
        env:
          RUST_LOG: "{{ forkmon_debug_level }}"
