- name: Stop validator client
  hosts: validator
  gather_facts: true
  serial: 20
  tasks:
    - name: Stop cl validator client container
      shell: "docker stop --time=10 {{validator_container_name}}"
      register: stop_result
      failed_when: "(stop_result.rc >= 1) and not ('No such container' in stop_result.stderr)"
