- name: Upload faucet data
  hosts: faucet
  gather_facts: true
  tasks:
    - name: Creates faucet dir
      file:
        path: "{{faucet_node_dir}}"
        state: directory
    - name: Move the forkmon config j2 template to remote
      template:
        src: faucet/config.json.j2
        dest:  "{{faucet_node_dir}}/config.json"
        mode: '755'
    - name: Move the forkmon index.html j2 template to remote
      template:
        src: faucet/index.html.j2
        dest: "{{faucet_node_dir}}/index.html"
        mode: '755'