version: "3.4"
services:
  postgres:
    image: postgres:12.0
    container_name: postgres
    volumes:
      - ./postgres_volumes:/src
    command: >
      -i -h 172.1.1.100
    networks:
        explorer_net:
            ipv4_address: 172.1.1.100
    environment:
      POSTGRES_PASSWORD: "stupidpassword"
      POSTGRES_USER: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: db
      PGDATA: "/postgresql/data"

networks:
  explorer_net:
    ipam:
      config:
        - subnet: 172.1.1.1/24