eth1_client_name: geth
eth1_image_name: parithoshj/geth:master-5f6e870

eth1_github_external_user_pubkeys:
  - mariusVanDerWijden

# bare websocket
eth1endpoint_ws: ws://127.0.0.1:8546

eth1_memory: 5000M
eth1_kernel_memory: 5500M


eth1_volumes:
  - "{{eth1_node_dir}}:/eth1data"
  - "{{testnet_dir}}:/networkdata"

eth1_start_args: >
  --datadir=/eth1data
  --sepolia
  --http --http.api "admin,net,eth"
  --http.port {{eth1_rpc_port}}
  --http.addr 0.0.0.0
  --http.corsdomain "*"
  --ws --ws.api "net,eth"
  --ws.port={{eth1_ws_rpc_port}}
  --ws.addr 0.0.0.0
  --nat extip:{{ansible_host}}
  --allow-insecure-unlock
  --vmodule=rpc=5
  --maxpeers=75
  --override.terminaltotaldifficulty=100000000000000000000000
  --syncmode=full
  --cache.preimages
  --bootnodes=enode://ce970ad2e9daa9e14593de84a8b49da3d54ccfdf83cbc4fe519cb8b36b5918ed4eab087dedd4a62479b8d50756b492d5f762367c8d20329a7854ec01547568a6@165.22.196.173:30303
  --mine --miner.threads=2 --miner.etherbase=0xfb969eb20eca70c2800103bbb0d3757bc60f918a
  --ethash.dagdir=/eth1data/ethash

eth1_user_id: "1000:1000"

# ./go-ethereum/build/bin/geth --datadir=./goerli-shadow-fork init genesis.json
# ./go-ethereum/build/bin/geth --authrpc.jwtsecret=/home/devops/jwtsecret --datadir=./goerli-shadow-fork --ethash.dagdir=./goerli-shadow-fork/ethash --mine --miner.threads=1 --miner.etherbase=0xfb969eb20eca70c2800103bbb0d3757bc60f918a --http --http.corsdomain='*' --http.addr="0.0.0.0" --http.api="engine,net,eth,debug,txpool"  --nat extip:164.90.177.4 --networkid=5 console
# ./go-ethereum/build/bin/geth --datadir=./goerli-shadow-fork --ethash.dagdir=./goerli-shadow-fork/ethash  --http --http.corsdomain='*' --http.addr="0.0.0.0" --http.vhosts="*" --http.api="engine,net,eth,debug,txpool" --ws --ws.api="eth,net,engine" --ws.port=8546 --ws.addr="0.0.0.0" --rpc.allow-unprotected-txs  --nat extip:164.90.177.4 --networkid=5 console
