##############################################
# generic ansible config information
##############################################
ansible_user: "devops"
bootstrap_user: "devops"

github_user_pubkeys:
  - parithosh
  - protolambda
  - ralexstokes
  - djrtwo
  - skylenet
  - jwasinger
  - gballet

ansible_python_interpreter: /usr/bin/python3
oh_my_zsh_config:
  PROMPT: "%{$fg[yellow]%}%n%{$fg[white]%}@%{$fg[red]%}%m%{$reset_color%} ${PROMPT}"


eth1endpoint: http://127.0.0.1:8545

##############################################
# testnet specific information
##############################################
testnet_type: custom
eth2_network_name: verkle-testnet
chainID: 69420

# enter bootnodes here if needed
eth1_bootnode_enode:
  - "enode://900c14b5bf3ed791f040b28c62e5e03838392078d30f93ee9b8d0c953012ae72900c9970fbfe62261daa7f14603fcf8d9c6cc4437e39dc46fa08193ca0903cfe@206.189.52.190:30303"

##############################################
# ports to configure
##############################################
eth1_rpc_port: 8545
eth1_ws_rpc_port: 8546
node_exporter_web_listen_address: "0.0.0.0:9100"

##############################################
# name of the validator to display
##############################################
graffiti: "{{eth2_client_name}}-{{eth1_client_name}}"

##############################################
# local data directories
##############################################
local_explorerdata_host_dir: "{{inventory_dir}}/../explorerdata"
local_explorerdata_host_archive: "{{inventory_dir}}/../explorerdata.tar.gz"
local_forkmondata_host_dir: "{{inventory_dir}}/../forkmondata"
local_forkmondata_host_archive: "{{inventory_dir}}/../forkmondata.tar.gz"
local_custom_config_data_host_dir: "{{inventory_dir}}/../custom_config_data"
local_custom_config_data_host_archive: "{{inventory_dir}}/../custom_config_data.tar.gz"


##############################################
# remote host data directories
##############################################
home_dir: "/home/{{ ansible_user }}"
testnet_dir: "{{home_dir}}/custom_config_data"
eth1_node_dir: "{{home_dir}}/eth1data"

##############################################
# common log config
##############################################
common_log_options:
  max-file: "10"
  max-size: 30m
  mode: non-blocking
  max-buffer-size: 4m
common_log_driver: json-file


##############################################
# container names
##############################################
hi_peer_count: 25

firewall_allowed_tcp_ports:
  - 22
  - 30303
  - 80
  - 443

firewall_allowed_udp_ports:
  - 30303

firewall_additional_rules:
  - "iptables -A INPUT -p tcp --dport 4000 -s 206.189.52.190 -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 8545 -s 206.189.52.190 -j ACCEPT"
