##############################################
# generic faucet info
##############################################
faucet_node_dir: "{{home_dir}}/faucet_data"
debug: false

##############################################
# captcha info
##############################################
hcaptcha_site_key: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/verkle/verkle-hcaptcha-site-key') }}"
hcaptcha_secret: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/verkle/verkle-hcaptcha-secret') }}"

##############################################
# faucet config
##############################################
ether_to_transfer: 10000000000000000000
rpc_url: https://rpc.condrieu.ethdevops.io
faucet_private_key: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/verkle/verkle-faucet-key') }}"
unit_name: "vETH"

##############################################
# faucet container info
##############################################
faucet_container_name: faucet
faucet_image_name: skylenet/fauceth:fix_fee_estimation
faucet_volumes:
  - "{{faucet_node_dir}}:/config"
