landing_page_dir: "{{home_dir}}/landing_page_data"

##############################################
# landing_page container info
##############################################
landing_page_container_name: landing_page
landing_page_image_name: skylenet/ethereum-testnet-homepage:latest
landing_page_require_restart: true
landing_page_volumes:
  - "{{landing_page_dir}}/config.yaml:/app/config.yaml"
  - "{{landing_page_dir}}/custom_text.md:/app/layouts/partials/custom.md"

landing_page_port: 1313
landing_page_ip: 172.1.1.108