certificates:
  rpc.condrieu.ethdevops.io:
    mode: http
  condrieu.ethdevops.io:
    mode: http
  faucet.condrieu.ethdevops.io:
    mode: http
  explorer.condrieu.ethdevops.io:
    mode: http
  ethstats.condrieu.ethdevops.io:
    mode: http

haproxy_frontends:
  - name: host_condrieu_rpc
    address: rpc.condrieu.ethdevops.io
    backend: host_condrieu_rpc
  - name: host_condrieu
    address: condrieu.ethdevops.io
    backend: host_condrieu
  - name: host_condrieu_faucet
    address: faucet.condrieu.ethdevops.io
    backend: host_condrieu_faucet
  - name: host_condrieu_explorer
    address: explorer.condrieu.ethdevops.io
    backend: host_condrieu_explorer
  - name: host_condrieu_ethstats
    address: ethstats.condrieu.ethdevops.io
    backend: host_condrieu_ethstats

haproxy_backend_servers:
  - name: host_condrieu_rpc
    address: localhost:8545
    options: 'check fall 3 rise 2'
  - name: host_condrieu
    address: 127.0.0.1:1313
    options: 'check fall 3 rise 2'
  - name: host_condrieu_faucet
    address: 127.0.0.1:8000
    options: 'check fall 3 rise 2'
  - name: host_condrieu_explorer
    address: localhost:4567
    options: 'check fall 3 rise 2'
  - name: host_condrieu_ethstats
    address: 127.0.0.1:3000
    options: 'check fall 3 rise 2'

haproxy_stats_port: 8404
haproxy_user: devops
haproxy_group: devops
haproxy_stats_user: devops
haproxy_stats_password: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/verkle/verkle-haproxy-key') }}"

haproxy_default_backend_name: host_condrieu
grafana_prometheus_network_name: explorernet

le_email: parithosh@ethereum.org
debian_certbot: false
