---
- name: Stop all containers
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Stop cl beacon node container
      shell: "docker stop --time=500 {{beacon_container_name}}"
      register: stop_result
      failed_when: "(stop_result.rc >= 1) and not ('No such container' in stop_result.stderr)"
    - name: Stop cl validator client container
      shell: "docker stop --time=500 {{validator_container_name}}"
      register: stop_result
      failed_when: "(stop_result.rc >= 1) and not ('No such container' in stop_result.stderr)"
    - name: Stop geth client container
      shell: "docker stop --time=500 {{el_client_name}}"
      register: stop_result
      failed_when: "(stop_result.rc >= 1) and not ('No such container' in stop_result.stderr)"
    - name: Remove beacon data
      become: true
      file:
        path: "{{beacon_node_dir}}"
        state: absent
    - name: Remove validator data
      become: true
      file:
        path: "{{validator_node_dir}}"
        state: absent
    - name: Remove testnet dir
      become: true
      when: (testnet_type == 'custom') or
        (testnet_type == 'prater' and cl_client_name == 'prysm')
      file:
        path: "{{testnet_dir}}"
        state: absent
    - name: Remove jwt secret
      become: true
      file:
        path: "{{ home_dir }}/jwtsecret"
        state: absent
    - name: Stop RPC snooper container
      shell: "docker rm -f {{snoop_container_name}}"
      register: stop_result
      failed_when: "(stop_result.rc >= 1) and not ('No such container' in stop_result.stderr)"
