- import_playbook: setup_landing_page_full.yml
- import_playbook: setup_reverse_proxy.yml
- import_playbook: setup_forkmon_full.yml
- import_playbook: setup_faucet_full.yml
- import_playbook: setup_ethstats_server.yml