- hosts: alertmanager
  become: yes
  tasks:
    - name: make sure alertmanager dir exists
      file:
        path: "{{ alertmanager_dir }}"
        state: directory
    - name: copy alert config
      template:
        src: tasks/templates/alertmanager/alerts-config.yml.j2
        dest: "{{ alertmanager_dir }}/alerts-config.yml"
        force: yes
    - name: copy alert rules
      copy:
        src: tasks/templates/alertmanager/base-rules.rules
        dest: "{{ alertmanager_dir }}/alert.rules"
        force: yes
    - name: start prometheus alert manager
      docker_container:
        name: alertmanager
        state: started
        restart: yes
        restart_policy: always
        volumes:
          - "{{alertmanager_dir}}:/etc/alertmanager"
        image: "{{ alertmanager_image }}"
        command: --config.file=/etc/alertmanager/alerts-config.yml --cluster.advertise-address=0.0.0.0:9093
        network_mode: bridge
        exposed_ports:
          - "9093"
        ports:
          - "9093:9093"