- name: Start txfuzz
  hosts: txfuzz
  gather_facts: true
  serial: 20
  tasks:
    - name: Start txfuzz
      docker_container:
        name: "{{ txfuzz_container_name }}"
        state: started
        image: "{{ txfuzz_image_name }}"
        pull: true
        restart_policy: unless-stopped
        network_mode: bridge
        restart: "{{ explorer_require_restart | default(false) }}"
        command: "{{txfuzz_start_args}}"