---
- name: Stop all containers
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Stop geth client container
      shell: "docker stop --time=10 {{eth1_client_name}}"
      register: stop_result
      failed_when: "(stop_result.rc >= 1) and not ('No such container' in stop_result.stderr)"