---
## stop any running beacon/validator/snooping docker image
- import_playbook: tasks/stop_beacon.yml
- import_playbook: tasks/stop_validator.yml
- import_playbook: tasks/stop_execution_node.yml
- import_playbook: tasks/stop_snooper.yml
  when: cl_client_name != 'nimbus'

#- name: delete dir
#  hosts: all
#  tasks:
#    - name: Remove custom_config_data dir
#      become: true
#      when: (testnet_type == 'custom') or
#            (testnet_type == 'prater' and cl_client_name == 'prysm')
#      file:
#        path: "{{testnet_dir}}"
#        state: absent
#    - name: Creates custom_config_data dir
#      file:
#        path: "{{testnet_dir}}"
#        state: directory
#
#- import_playbook: tasks/upload_custom_config_data.yml
#  when: (testnet_type == 'custom') or
#        (testnet_type == 'prater' and cl_client_name == 'prysm')

- import_playbook: tasks/init_geth_node.yml
  when: (testnet_type == 'custom') and
    (el_client_name == 'geth' or el_client_name == 'erigon')

# starts execution node docker container
- import_playbook: tasks/start_execution_node.yml

# starts the json rpc snooper
- import_playbook: tasks/start_snooper.yml

# stars beacon node docker container
- import_playbook: tasks/start_beacon.yml

# stars validator docker container
- import_playbook: tasks/start_validator.yml
  when: (separate_validator_process_enabled) and (no_validator_keys != 'true')

# - import_playbook: tasks/setup_node_exporter_and_prometheus.yml
#   when: push_metrics_enabled
