---
- name: Wipe all!!
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Stop execution client container
      shell: "docker stop --time=10 {{el_client_name}}"
      register: stop_result
      failed_when: "(stop_result.rc >= 1) and not ('No such container' in stop_result.stderr)"
    - name: Stop snooper container
      shell: "docker stop --time=10 {{snoop_container_name}}"
      register: stop_result
      failed_when: "(stop_result.rc >= 1) and not ('No such container' in stop_result.stderr)"
    - name: Remove execution data
      become: true
      file:
        path: "{{el_node_dir}}"
        state: absent
    - name: Remove testnet dir
      become: true
      when: (testnet_type == 'custom') or
            (testnet_type == 'prater' and eth2_client_name == 'prysm')
      file:
        path: "{{testnet_dir}}"
        state: absent
#     - name: Stop node_exporter service
#       systemd:
#         state: stopped
#         name: node_exporter
#       ignore_errors: yes
#     - name: Stop prometheus service
#       systemd:
#         state: stopped
#         name: prometheus
#       ignore_errors: yes
#     - name: Disable node exporter
#       systemd:
#         name: node_exporter
#         enabled: no
#         masked: no
#       ignore_errors: yes
#     - name: Disable prometheus
#       systemd:
#         name: prometheus
#         enabled: no
#         masked: no
#       ignore_errors: yes
#     - name: Delete the systemD unit file
#       file:
#         path: /etc/systemd/system/node_exporter.service
#         state: absent
#     - name: Delete the systemD unit file
#       file:
#         path: /etc/systemd/system/prometheus.service
#         state: absent
#     - name: Reload systemD
#       systemd:
#         daemon_reload: yes
#     - name: Delete the bin
#       file:
#         path: /usr/local/bin/node_exporter
#         state: absent
#     - name: Delete user
#       user:
#         name: node_exp
#         state: absent
#         group: node_exp
#         shell: "/sbin/nologin"
#     - name: Delete user
#       user:
#         name: prometheus
#         state: absent
#         group: prometheus
#         shell: "/sbin/nologin"
#     - name: Delete the node exporter config
#       file:
#         path: /etc/default/node_exporter
#         state: absent
#     - name: Delete the prometheus config
#       file:
#         path: /etc/default/prometheus
#         state: absent