---
#
# Ansible managed
#
repository:
  description: Install and configure fail2ban on your system.
  homepage: https://robertdebock.nl/
  topics: fail2ban, installer, package, ansible, molecule, tox, playbook, hacktoberfest
